language: python
python: 3.10
dist: jammy
sudo: true
matrix:
  include:
    - os: linux
      dist: jammy
      python: 3.10
      sudo: true
      before_install:
        - pip install -U pip
        - pip install -r requirements-dev.txt
        - python setup.py install
    - os: windows
      language: sh
      python: "3.10"
      env: export PATH="/c/Python39:/c/Python39/Scripts:$PATH"
      before_install:
        - choco install python3
        - pip install -u pip
        - python -m pip install -r requirements-dev.txt
        - python setup.py install
    - os: osx
      osx_image: xcode10.2
      language: shell
      before_install:
        - pip install -U pip
        - pip3 install -r requirements-dev.txt
        - python3 setup.py install
      script:
        - python3 -m pytest --cov litedb
script:
    - pytest --cov litedb
after_success:
    - coveralls
